package Vista;

import javax.swing.*;

/**
 *
 * @author LUIS
 */
public class VentanaPrimerosPasos extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrimerosPasos
     */
    public VentanaPrimerosPasos() {
        initComponents();
        // Centrar ventana y evitar que cierre el programa
        setLocationRelativeTo(null); // Centrado en pantalla (o puedes usar setLocationRelativeTo(Sistema.this))
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE); // Solo cierra esta ventana

        // Opcional: impedir redimensionar
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Primeros Pasos - Guía Rápida de Uso");

        jLabel1.setText("<html>     <div style='text-align: center; font-family: Segoe UI, sans-serif;'>         <h2>Primeros Pasos</h2>         <p>             Bienvenido al sistema de gestión empresarial <strong>TecnoLuis-GestionStock</strong>.         </p>         <p>             Esta aplicación te permite controlar <strong>ventas, productos, clientes, proveedores</strong> y gestionar usuarios según su rol.         </p>         <p>             Para comenzar:             <ul style='text-align: left; display: inline-block;'>                 <li>Inicia sesión con tus credenciales (correo y contraseña).</li>                 <li>El sistema distingue entre <strong>Administrador</strong> (acceso completo) y <strong>Vendedor</strong> (acceso limitado).</li>                 <li>Solo los Administradores pueden registrar, editar o eliminar usuarios.</li>                 <li>Accede al menú lateral para navegar entre módulos como <strong>Nueva Venta, Productos, Clientes</strong> y <strong>Proveedores</strong>.</li>                 <li>Desde <strong>Configuración</strong> puedes actualizar los datos fiscales de la empresa (solo Administradores).</li>             </ul>         </p>         <p>             Explora cada módulo paso a paso. Si necesitas más detalles,<br>             accede al <strong>Manual de Usuario</strong> desde el menú de Ayuda.         </p>     </div> </html> ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrimerosPasos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrimerosPasos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrimerosPasos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrimerosPasos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrimerosPasos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
