/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import javax.swing.*;

/**
 *
 * @author LUIS
 */
public class VentanaManualUsuario extends javax.swing.JFrame {

    /**
     * Creates new form VentanaManualUsuario
     */
    public VentanaManualUsuario() {
        initComponents();

        // Centrar ventana y evitar que cierre el programa
        setLocationRelativeTo(null); // Centrado en pantalla (o puedes usar setLocationRelativeTo(Sistema.this))
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE); // Solo cierra esta ventana

        // Opcional: impedir redimensionar
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Manual de Usuario - Instrucciones Completas");

        jLabel1.setText("<html>     <div style='text-align: center; font-family: Segoe UI, sans-serif;'>         <h2>Manual de Usuario</h2>         <p>             Este sistema está diseñado para facilitar la gestión de los procesos operativos de una empresa.         </p>         <p>             <strong>Módulos principales:</strong>             <ul style='text-align: left; display: inline-block;'>                 <li><strong>Usuarios:</strong> Alta, baja y modificación de usuarios del sistema.</li>                 <li><strong>Clientes:</strong> Registro y edición de clientes habituales.</li>                 <li><strong>Proveedores:</strong> Gestión de empresas proveedoras.</li>                 <li><strong>Productos:</strong> Gestión de artículos disponibles, stock y precios.</li>                 <li><strong>Ventas:</strong> Registro de transacciones comerciales y generación de reportes.</li>                 <li><strong>Configuración:</strong> Datos generales de la empresa y ajustes básicos.</li>             </ul>         </p>         <p>             El sistema permite generar <strong>reportes en PDF</strong> y <strong>exportar datos a Excel</strong> con un solo clic.<br>             También podrás ver gráficos por fecha para tener una visión clara de tus ventas.         </p>         <p>             Para cualquier duda, contacta al desarrollador: <br>             <a href='mailto:luisprado89@gmail.com'>luisprado89@gmail.com</a>         </p>     </div> </html> ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 623, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 626, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaManualUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaManualUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaManualUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaManualUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaManualUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
