package Vista;

import javax.swing.*;
import java.awt.*;
import java.io.*;
import java.net.URL;
import java.nio.charset.StandardCharsets;

/**
 *
 * @author LUIS
 */
public class VentanaManualUsuario extends javax.swing.JFrame {

    /**
     * Creates new form VentanaManualUsuario
     */
    public VentanaManualUsuario() {
        initComponents();
        setResizable(false);

        // Centrar ventana y evitar que cierre el programa
        setLocationRelativeTo(null); // Centrado en pantalla (o puedes usar setLocationRelativeTo(Sistema.this))
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE); // Solo cierra esta ventana



        cargarManualDesdeArchivo();  //  Cargar el HTML desde el paquete Util
    }
    private void cargarManualDesdeArchivo() {
        try {
            InputStream is = getClass().getClassLoader().getResourceAsStream("Util/ManualCompleto.html");
            if (is != null) {
                BufferedReader br = new BufferedReader(new InputStreamReader(is, StandardCharsets.UTF_8));
                StringBuilder sb = new StringBuilder();
                String linea;
                while ((linea = br.readLine()) != null) {
                    sb.append(linea);
                }
                br.close();

                //jEditorPane1.setContentType("text/html");
                //jEditorPane1.setText(sb.toString());

                URL url = getClass().getClassLoader().getResource("Util/ManualCompleto.html");
                if (url != null) {
                    jEditorPane1.setPage(url);
                } else {
                    jEditorPane1.setText("<html><body><h2>No se encontró el archivo HTML</h2></body></html>");
                }


                jEditorPane1.setEditable(false);
                jScrollPane1.setViewportView(jEditorPane1);
            } else {
                jEditorPane1.setText("<html><body><h2>No se encontró el archivo ManualCompleto.html</h2></body></html>");
            }
        } catch (IOException e) {
            jEditorPane1.setText("<html><body><h2>Error al cargar el manual</h2><p>" + e.getMessage() + "</p></body></html>");
            e.printStackTrace();
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Manual de Usuario - Instrucciones Completas");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 80, 45, 45));

        jScrollPane1.setViewportView(jEditorPane1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-5, 0, 1150, 860));

        jMenu1.setText("Guía de Uso (PDF)  ");

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/pdf_32.png"))); // NOI18N
        jMenuItem1.setText("Abrir PDF");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // Abre el PDF del manual de usuario ubicado en src/Util/ManualUsuarioCompleto.pdf
        try {
            File manual = new File("src/Util/ManualUsuarioCompleto.pdf");
            if (manual.exists()) {
                Desktop.getDesktop().open(manual);
            } else {
                JOptionPane.showMessageDialog(this, "No se encontró el archivo: src/Util/ManualUsuarioCompleto.pdf");
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error al abrir el manual: " + e.getMessage());
        }


    }//GEN-LAST:event_jMenuItem1ActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaManualUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaManualUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaManualUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaManualUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaManualUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
